/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "5.0.1",
                minimumCompatibleVersion: "5.0.0",
                build: "5.0.1.386",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'CLA_new_paper3',
                            type: 'image',
                            rect: ['111px', '20px', '332px', '333px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"CLA_new_paper3.svg",'0px','0px']
                        },
                        {
                            id: 'CLA_new_signature',
                            display: 'block',
                            type: 'image',
                            rect: ['109px', '19px', '60.4%', '333px', 'auto', 'auto'],
                            opacity: '1',
                            fill: ["rgba(0,0,0,0)",im+"CLA_new_signature.svg",'0px','0px']
                        },
                        {
                            id: 'Rectangle3',
                            display: 'block',
                            type: 'rect',
                            rect: ['226px', '226px', '80px', '25px', 'auto', 'auto'],
                            fill: ["rgba(230,230,230,1.00)"],
                            stroke: [0,"rgb(0, 0, 0)","none"]
                        },
                        {
                            id: 'Rectangle4',
                            display: 'block',
                            type: 'rect',
                            rect: ['253px', '228px', '90px', '68px', 'auto', 'auto'],
                            borderRadius: ["8.8%", "8.8%", "8.8%", "8.8% 8.8%"],
                            fill: ["rgba(230,230,230,1)"],
                            stroke: [0,"rgb(0, 0, 0)","solid"]
                        },
                        {
                            id: 'CLA_new_pen',
                            type: 'image',
                            rect: ['109px', '19px', '332px', '333px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"CLA_new_pen.svg",'0px','0px']
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '550px', '400px', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,1)"]
                        }
                    }
                },
                timeline: {
                    duration: 1000,
                    autoPlay: true,
                    data: [
                        [
                            "eid228",
                            "border-bottom-right-radius",
                            126,
                            0,
                            "linear",
                            "${Rectangle4}",
                            [8.8,8.8],
                            [8.8,8.8],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid150",
                            "left",
                            0,
                            65,
                            "linear",
                            "${Rectangle3}",
                            '226px',
                            '231px'
                        ],
                        [
                            "eid151",
                            "left",
                            65,
                            61,
                            "linear",
                            "${Rectangle3}",
                            '231px',
                            '250px'
                        ],
                        [
                            "eid152",
                            "left",
                            126,
                            124,
                            "linear",
                            "${Rectangle3}",
                            '250px',
                            '258px'
                        ],
                        [
                            "eid153",
                            "left",
                            250,
                            78,
                            "linear",
                            "${Rectangle3}",
                            '258px',
                            '280px'
                        ],
                        [
                            "eid154",
                            "left",
                            328,
                            87,
                            "linear",
                            "${Rectangle3}",
                            '280px',
                            '285px'
                        ],
                        [
                            "eid155",
                            "left",
                            415,
                            123,
                            "linear",
                            "${Rectangle3}",
                            '285px',
                            '300px'
                        ],
                        [
                            "eid156",
                            "left",
                            538,
                            116,
                            "linear",
                            "${Rectangle3}",
                            '300px',
                            '308px'
                        ],
                        [
                            "eid157",
                            "left",
                            654,
                            346,
                            "linear",
                            "${Rectangle3}",
                            '308px',
                            '225px'
                        ],
                        [
                            "eid227",
                            "border-top-right-radius",
                            126,
                            0,
                            "linear",
                            "${Rectangle4}",
                            [8.8,8.8],
                            [8.8,8.8],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid175",
                            "background-color",
                            0,
                            65,
                            "linear",
                            "${Rectangle4}",
                            'rgba(230,230,230,1)',
                            'rgba(230,230,230,1.00)'
                        ],
                        [
                            "eid219",
                            "left",
                            65,
                            0,
                            "linear",
                            "${Rectangle4}",
                            '253px',
                            '253px'
                        ],
                        [
                            "eid179",
                            "left",
                            126,
                            82,
                            "linear",
                            "${Rectangle4}",
                            '253px',
                            '251px'
                        ],
                        [
                            "eid184",
                            "left",
                            208,
                            42,
                            "linear",
                            "${Rectangle4}",
                            '251px',
                            '262px'
                        ],
                        [
                            "eid186",
                            "left",
                            250,
                            78,
                            "linear",
                            "${Rectangle4}",
                            '262px',
                            '284px'
                        ],
                        [
                            "eid187",
                            "left",
                            328,
                            39,
                            "linear",
                            "${Rectangle4}",
                            '284px',
                            '284px'
                        ],
                        [
                            "eid229",
                            "left",
                            367,
                            48,
                            "linear",
                            "${Rectangle4}",
                            '284px',
                            '289px'
                        ],
                        [
                            "eid188",
                            "left",
                            415,
                            123,
                            "linear",
                            "${Rectangle4}",
                            '289px',
                            '304px'
                        ],
                        [
                            "eid189",
                            "left",
                            538,
                            116,
                            "linear",
                            "${Rectangle4}",
                            '304px',
                            '312px'
                        ],
                        [
                            "eid190",
                            "left",
                            654,
                            280,
                            "linear",
                            "${Rectangle4}",
                            '312px',
                            '223px'
                        ],
                        [
                            "eid213",
                            "left",
                            934,
                            66,
                            "linear",
                            "${Rectangle4}",
                            '223px',
                            '229px'
                        ],
                        [
                            "eid17",
                            "top",
                            0,
                            65,
                            "linear",
                            "${CLA_new_pen}",
                            '25px',
                            '0px'
                        ],
                        [
                            "eid21",
                            "top",
                            65,
                            61,
                            "linear",
                            "${CLA_new_pen}",
                            '0px',
                            '-20px'
                        ],
                        [
                            "eid18",
                            "top",
                            126,
                            124,
                            "linear",
                            "${CLA_new_pen}",
                            '-20px',
                            '20px'
                        ],
                        [
                            "eid23",
                            "top",
                            250,
                            78,
                            "linear",
                            "${CLA_new_pen}",
                            '20px',
                            '11px'
                        ],
                        [
                            "eid28",
                            "top",
                            328,
                            87,
                            "linear",
                            "${CLA_new_pen}",
                            '11px',
                            '29px'
                        ],
                        [
                            "eid26",
                            "top",
                            415,
                            123,
                            "linear",
                            "${CLA_new_pen}",
                            '29px',
                            '26px'
                        ],
                        [
                            "eid53",
                            "top",
                            538,
                            116,
                            "linear",
                            "${CLA_new_pen}",
                            '26px',
                            '19px'
                        ],
                        [
                            "eid54",
                            "top",
                            654,
                            346,
                            "linear",
                            "${CLA_new_pen}",
                            '19px',
                            '26px'
                        ],
                        [
                            "eid226",
                            "border-top-left-radius",
                            126,
                            0,
                            "linear",
                            "${Rectangle4}",
                            [8.8,8.8],
                            [8.8,8.8],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid237",
                            "display",
                            92,
                            0,
                            "linear",
                            "${Rectangle3}",
                            'block',
                            'none'
                        ],
                        [
                            "eid162",
                            "display",
                            126,
                            0,
                            "linear",
                            "${Rectangle3}",
                            'none',
                            'none'
                        ],
                        [
                            "eid217",
                            "display",
                            208,
                            0,
                            "linear",
                            "${Rectangle3}",
                            'none',
                            'none'
                        ],
                        [
                            "eid16",
                            "left",
                            0,
                            65,
                            "linear",
                            "${CLA_new_pen}",
                            '27px',
                            '32px'
                        ],
                        [
                            "eid20",
                            "left",
                            65,
                            61,
                            "linear",
                            "${CLA_new_pen}",
                            '32px',
                            '51px'
                        ],
                        [
                            "eid19",
                            "left",
                            126,
                            124,
                            "linear",
                            "${CLA_new_pen}",
                            '51px',
                            '59px'
                        ],
                        [
                            "eid22",
                            "left",
                            250,
                            78,
                            "linear",
                            "${CLA_new_pen}",
                            '59px',
                            '81px'
                        ],
                        [
                            "eid29",
                            "left",
                            328,
                            87,
                            "linear",
                            "${CLA_new_pen}",
                            '81px',
                            '86px'
                        ],
                        [
                            "eid27",
                            "left",
                            415,
                            123,
                            "linear",
                            "${CLA_new_pen}",
                            '86px',
                            '101px'
                        ],
                        [
                            "eid52",
                            "left",
                            538,
                            116,
                            "linear",
                            "${CLA_new_pen}",
                            '101px',
                            '109px'
                        ],
                        [
                            "eid55",
                            "left",
                            654,
                            346,
                            "linear",
                            "${CLA_new_pen}",
                            '109px',
                            '26px'
                        ],
                        [
                            "eid215",
                            "display",
                            654,
                            0,
                            "linear",
                            "${CLA_new_signature}",
                            'block',
                            'none'
                        ],
                        [
                            "eid178",
                            "height",
                            0,
                            65,
                            "linear",
                            "${Rectangle3}",
                            '42px',
                            '25px'
                        ],
                        [
                            "eid142",
                            "top",
                            0,
                            65,
                            "linear",
                            "${Rectangle3}",
                            '226px',
                            '223px'
                        ],
                        [
                            "eid143",
                            "top",
                            65,
                            61,
                            "linear",
                            "${Rectangle3}",
                            '223px',
                            '181px'
                        ],
                        [
                            "eid144",
                            "top",
                            126,
                            124,
                            "linear",
                            "${Rectangle3}",
                            '181px',
                            '221px'
                        ],
                        [
                            "eid145",
                            "top",
                            250,
                            78,
                            "linear",
                            "${Rectangle3}",
                            '221px',
                            '212px'
                        ],
                        [
                            "eid146",
                            "top",
                            328,
                            87,
                            "linear",
                            "${Rectangle3}",
                            '212px',
                            '230px'
                        ],
                        [
                            "eid147",
                            "top",
                            415,
                            123,
                            "linear",
                            "${Rectangle3}",
                            '230px',
                            '227px'
                        ],
                        [
                            "eid148",
                            "top",
                            538,
                            116,
                            "linear",
                            "${Rectangle3}",
                            '227px',
                            '220px'
                        ],
                        [
                            "eid149",
                            "top",
                            654,
                            346,
                            "linear",
                            "${Rectangle3}",
                            '220px',
                            '227px'
                        ],
                        [
                            "eid165",
                            "top",
                            65,
                            61,
                            "linear",
                            "${Rectangle4}",
                            '228px',
                            '226px'
                        ],
                        [
                            "eid180",
                            "top",
                            126,
                            38,
                            "linear",
                            "${Rectangle4}",
                            '226px',
                            '241px'
                        ],
                        [
                            "eid168",
                            "top",
                            164,
                            44,
                            "linear",
                            "${Rectangle4}",
                            '241px',
                            '254px'
                        ],
                        [
                            "eid191",
                            "top",
                            250,
                            78,
                            "linear",
                            "${Rectangle4}",
                            '254px',
                            '248px'
                        ],
                        [
                            "eid192",
                            "top",
                            328,
                            39,
                            "linear",
                            "${Rectangle4}",
                            '248px',
                            '263px'
                        ],
                        [
                            "eid230",
                            "top",
                            367,
                            48,
                            "linear",
                            "${Rectangle4}",
                            '263px',
                            '266px'
                        ],
                        [
                            "eid193",
                            "top",
                            415,
                            123,
                            "linear",
                            "${Rectangle4}",
                            '266px',
                            '263px'
                        ],
                        [
                            "eid194",
                            "top",
                            538,
                            116,
                            "linear",
                            "${Rectangle4}",
                            '263px',
                            '256px'
                        ],
                        [
                            "eid195",
                            "top",
                            654,
                            229,
                            "linear",
                            "${Rectangle4}",
                            '256px',
                            '225px'
                        ],
                        [
                            "eid208",
                            "top",
                            883,
                            51,
                            "linear",
                            "${Rectangle4}",
                            '225px',
                            '219px'
                        ],
                        [
                            "eid212",
                            "top",
                            934,
                            66,
                            "linear",
                            "${Rectangle4}",
                            '219px',
                            '263px'
                        ],
                        [
                            "eid164",
                            "height",
                            65,
                            61,
                            "linear",
                            "${Rectangle4}",
                            '53px',
                            '56px'
                        ],
                        [
                            "eid181",
                            "height",
                            126,
                            38,
                            "linear",
                            "${Rectangle4}",
                            '56px',
                            '40px'
                        ],
                        [
                            "eid167",
                            "height",
                            164,
                            44,
                            "linear",
                            "${Rectangle4}",
                            '40px',
                            '27px'
                        ],
                        [
                            "eid197",
                            "height",
                            250,
                            78,
                            "linear",
                            "${Rectangle4}",
                            '27px',
                            '33px'
                        ],
                        [
                            "eid198",
                            "height",
                            328,
                            87,
                            "linear",
                            "${Rectangle4}",
                            '33px',
                            '22px'
                        ],
                        [
                            "eid199",
                            "height",
                            415,
                            123,
                            "linear",
                            "${Rectangle4}",
                            '22px',
                            '26px'
                        ],
                        [
                            "eid207",
                            "height",
                            796,
                            87,
                            "linear",
                            "${Rectangle4}",
                            '26px',
                            '62px'
                        ],
                        [
                            "eid210",
                            "height",
                            883,
                            51,
                            "linear",
                            "${Rectangle4}",
                            '62px',
                            '68px'
                        ],
                        [
                            "eid176",
                            "background-color",
                            0,
                            0,
                            "linear",
                            "${Rectangle3}",
                            'rgba(230,230,230,1.00)',
                            'rgba(230,230,230,1.00)'
                        ],
                        [
                            "eid177",
                            "background-color",
                            65,
                            0,
                            "linear",
                            "${Rectangle3}",
                            'rgba(230,230,230,1.00)',
                            'rgba(230,230,230,1.00)'
                        ],
                        [
                            "eid182",
                            "width",
                            0,
                            126,
                            "linear",
                            "${Rectangle4}",
                            '60px',
                            '63px'
                        ],
                        [
                            "eid183",
                            "width",
                            126,
                            38,
                            "linear",
                            "${Rectangle4}",
                            '63px',
                            '60px'
                        ],
                        [
                            "eid185",
                            "width",
                            164,
                            44,
                            "linear",
                            "${Rectangle4}",
                            '60px',
                            '68px'
                        ],
                        [
                            "eid171",
                            "width",
                            208,
                            42,
                            "linear",
                            "${Rectangle4}",
                            '68px',
                            '51px'
                        ],
                        [
                            "eid211",
                            "width",
                            250,
                            250,
                            "linear",
                            "${Rectangle4}",
                            '51px',
                            '36px'
                        ],
                        [
                            "eid214",
                            "width",
                            500,
                            434,
                            "linear",
                            "${Rectangle4}",
                            '36px',
                            '90px'
                        ],
                        [
                            "eid159",
                            "display",
                            0,
                            0,
                            "linear",
                            "${Rectangle4}",
                            'block',
                            'block'
                        ],
                        [
                            "eid158",
                            "display",
                            65,
                            0,
                            "linear",
                            "${Rectangle4}",
                            'block',
                            'block'
                        ],
                        [
                            "eid216",
                            "display",
                            654,
                            0,
                            "linear",
                            "${Rectangle4}",
                            'block',
                            'none'
                        ],
                        [
                            "eid225",
                            "border-bottom-left-radius",
                            126,
                            0,
                            "linear",
                            "${Rectangle4}",
                            [8.8,8.8],
                            [8.8,8.8],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("cla_edgeActions.js");
})("EDGE-23558314");
